routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [App\Http\Controllers\IndexController::class, 'index'])->name('index');
Route::resource('categories_of_products', App\Http\Controllers\CategoryOfProductsController::class);
Route::resource('products', App\Http\Controllers\ProductController::class)->except('index');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::fallback(function () {
    return abort(404);
});

app/Models/CategoryOfProducts.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class CategoryOfProducts extends Model
{
    protected $fillable = [
        'name'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function products()
    {
        return $this->hasMany(Product::class);
    }
}

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Product extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'category_of_products_id',
        'price',
        'quantity',
        'body'
    ];

  /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function category_of_products()
    {
        return $this->belongsTo(CategoryOfProducts::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'is_admin'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/CategoryOfProductsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CategoryOfProductsRequest;
use App\Models\CategoryOfProducts;
use Illuminate\Http\Request;

class CategoryOfProductsController extends Controller
{
    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function create()
    {
        $categories_of_products = CategoryOfProducts::all();

        return view('categories_of_products.create', compact('categories_of_products'));
    }

    /**
     * @param CategoryOfProductsRequest $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(CategoryOfProductsRequest $request)
    {
        $category_of_products = new CategoryOfProducts($request->all());
        $category_of_products->save();

        return redirect('categories_of_products/create')->with('status', 'Создана категория ' . $category_of_products->name);
    }

    /**
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function edit($id)
    {
        $category_of_products = CategoryOfProducts::findOrFail($id);

        return view('categories_of_products.edit', compact('category_of_products'));
    }

    /**
     * @param Request $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function update(Request $request, $id)
    {
        $category_of_products = CategoryOfProducts::findOrFail($id);
        $this->authorize('update', $category_of_products);
        $category_of_products->update($request->all());

        return back()->with('status', 'Категория изменена на ' . $category_of_products->name);
    }

    /**
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id)
    {
        $category_of_products = CategoryOfProducts::findOrFail($id);
        $category_of_products->delete();

        return back()->with('status', 'Категория удалена');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Support\Facades\Auth;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;

    /**
     * @return bool
     */
    public function checkForAdmin()
    {
        if (Auth::check() && Auth::User()->is_admin) {
            return true;
        } else {
            return false;
        }
    }

}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/IndexController.php
<?php

namespace App\Http\Controllers;

use App\Models\CategoryOfProducts;
use App\Models\Product;
use Illuminate\Http\Request;

class IndexController extends Controller
{
    public function index()
    {
        $categories_of_products = CategoryOfProducts::all();
        $products = Product::all();

        return view('index', compact('categories_of_products', 'products'));
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ProductRequest;
use App\Models\CategoryOfProducts;
use App\Models\Product;

class ProductController extends Controller
{

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function create()
    {
        $categories_of_products = CategoryOfProducts::all();

        return view('products.create', compact('categories_of_products'));
    }

    /**
     * @param ProductRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(ProductRequest $request)
    {
        $product = new Product($request->all());
        $product->save();

        return back()->with('status', 'Добавлен продукт ' . $product->name);
    }

    /**
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function show($id)
    {
        $product = Product::findOrFail($id);

        return view('products.show', compact('product'));
    }

    /**
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function edit($id)
    {
        if ($this->checkForAdmin()) {
            $product = Product::findOrFail($id);
            $categories_of_products = CategoryOfProducts::all();

            return view('products.edit', compact('product', 'categories_of_products'));
        } else {
            return redirect('/');
        }

    }

    /**
     * @param ProductRequest $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function update(ProductRequest $request, $id)
    {
        $product = Product::findOrFail($id);
        $this->authorize('update', $product);
        $product->update($request->all());

        return back()->with('status', 'Вы отредактировали продукт ' . $product->name);
    }

    /**
     * @param $id
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function destroy($id)
    {
        $product = Product::findOrFail($id);
        $deleted_product = $product->name;
        $product->delete();

        return redirect('/')->with('status', 'Вы удалили ' . $deleted_product);
    }
}

resources/views/categories_of_products/create.blade.php
@extends('layouts.app')

@section('content')

    <form method="post" action="{{route('categories_of_products.store')}}">
        @csrf
        <div class="form-group">
            <label for="name">Название категории</label>
            <input type="text" class="form-control @error('name') is-invalid @enderror" id="name" name="name">
            @error('name')
            <p class="text-danger">{{ $message }}</p>
            @enderror
        </div>

        <button type="submit" class="btn btn-success">Создать</button>
    </form>

    <table class="table table-bordered">
        <tbody>
        @foreach($categories_of_products as $category_of_products)
            <tr>
                <td>{{$category_of_products->name}}</td>
                <td><a href="{{route('categories_of_products.edit', ['categories_of_product' => $category_of_products])}}">Редактировать</a></td>
                <td>
                    <form method="post" action="{{route('categories_of_products.destroy', ['categories_of_product' => $category_of_products])}}">
                        @method('delete')
                        @csrf
                        <button type="submit" class="btn btn-outline-danger">Удалить</button>
                    </form>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>

    <div class="mt-3 mb-3">
        <a href="{{route('index')}}">Назад</a>
    </div>

@endsection

resources/views/categories_of_products/edit.blade.php
@extends('layouts.app')

@section('content')

    <h3 class="mb-2 mt-2">{{$category_of_products->name}}</h3>

    <form method="post" action="{{route('categories_of_products.update', ['categories_of_product' => $category_of_products])}}">
        @csrf
        @method('put')
        <div class="form-group">
            <label for="name">Название категории</label>
            <input type="text" class="form-control @error('name') is-invalid @enderror" id="name" name="name" value="{{$category_of_products->name}}">
            @error('name')
            <p class="text-danger">{{ $message }}</p>
            @enderror
        </div>

        <button type="submit" class="btn btn-success">Редактировать</button>
    </form>

    <div class="mt-3 mb-3">
        <a href="{{route('categories_of_products.create')}}">Назад</a>
    </div>

@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/index.blade.php
@extends('layouts.app')

@section('content')

    <h2>Категории продуктов</h2>

    @can('viewAny', Auth::User())
    <div>
        <a href="{{route('categories_of_products.create')}}" class="text-success">Добавить или отредактировать категорию</a>
    </div>
    @endcan

    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Название</th>
            </tr>
        </thead>
        <tbody>

            @php($categories_count = 0)
            @foreach($categories_of_products as $category_of_product)
                @php($categories_count = $categories_count + 1)
                <tr>
                    <th scope="row">{{$categories_count}}</th>
                    <td>{{$category_of_product->name}}</td>
                </tr>
            @endforeach

        </tbody>
    </table>

    <h2>Все продукты</h2>

    @can('viewAny', Auth::User())
    <div>
        <a href="{{route('products.create')}}" class="text-success">Добавить продукт</a>
    </div>
    @endcan

    <table class="table table-striped table-dark">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Название</th>
            <th scope="col">Цена</th>
            <th scope="col">Количество</th>
            <th scope="col">Категория</th>
        </tr>
        </thead>
        <tbody>
            @php($product_count = 0)
            @foreach($products as $product)
                @php($product_count = $product_count + 1)
            <tr>
                    <th scope="row">{{$product_count}}</th>
                    <td><a href="{{route('products.show', ['product' => $product])}}">{{$product->name}}</a></td>
                    <td>{{$product->price}}</td>
                    <td>{{$product->quantity}}</td>
                    <td>{{$product->category_of_products->name}}</td>
            </tr>
        @endforeach
        </tbody>
    </table>

@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Store') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Store') }}
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav me-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ms-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="container py-4">
            @if(session('status'))
                <div class="alert alert-primary" role="alert">
                    {{session('status')}}
                </div>
            @endif
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/products/create.blade.php
@extends('layouts.app')

@section('content')

    <h2>Добавление продукта</h2>

    <form method="post" action="{{route('products.store')}}">
        @csrf
        <div class="form-group">
            <label for="name">Название</label>
            <input type="text" class="form-control @error('name') is-invalid @enderror" id="name" name="name">
            @error('name')
            <p class="text-danger">{{ $message }}</p>
            @enderror
        </div>

        <div class="form-group">
            <label for="category_of_products_id">Категория</label>
            <select multiple class="form-control" id="category_of_products_id" name="category_of_products_id">
                @foreach($categories_of_products as $category_of_products)
                    <option value="{{$category_of_products->id}}">{{$category_of_products->name}}</option>
                @endforeach
            </select>

            @error('category_of_products_id')
            <p class="text-danger">{{ $message }}</p>
            @enderror
        </div>

        <div class="form-group">
            <label for="price">Цена</label>
            <input type="text" class="form-control @error('price') is-invalid @enderror" id="price" name="price">
            @error('price')
            <p class="text-danger">{{ $message }}</p>
            @enderror
        </div>

        <div class="form-group">
            <label for="quantity">Количество</label>
            <input type="text" class="form-control @error('quantity') is-invalid @enderror" id="quantity" name="quantity">
            @error('quantity')
            <p class="text-danger">{{ $message }}</p>
            @enderror
        </div>

        <div class="form-group">
            <label for="body">Описание</label>
            <textarea class="form-control @error('body') is-invalid @enderror" id="body" name="body" rows="3"></textarea>
            @error('body')
            <p class="text-danger">{{ $message }}</p>
            @enderror
        </div>

        <button type="submit" class="btn btn-success">Создать</button>

    </form>

    <div class="mt-3 mb-3">
        <a href="{{route('index')}}">Назад</a>
    </div>

@endsection

resources/views/products/edit.blade.php
@extends('layouts.app')

@section('content')

    <h2>Редактирование продукта</h2>

    <form method="post" action="{{route('products.update', ['product' => $product])}}">
        @csrf
        @method('put')
        <div class="form-group">
            <label for="name">Название</label>
            <input type="text" class="form-control @error('name') is-invalid @enderror" id="name" name="name" value="{{$product->name}}">
            @error('name')
            <p class="text-danger">{{ $message }}</p>
            @enderror
        </div>

        <div class="form-group">
            <label for="category_of_products_id">Категория</label>
            <select multiple class="form-control" id="category_of_products_id" name="category_of_products_id">
                @foreach($categories_of_products as $category_of_products)
                    <option value="{{$category_of_products->id}}"
                            @if($product->category_of_products->id == $category_of_products->id) selected @endif>
                        {{$category_of_products->name}}
                    </option>
                @endforeach
            </select>

            @error('category_of_products_id')
            <p class="text-danger">{{ $message }}</p>
            @enderror
        </div>

        <div class="form-group">
            <label for="price">Цена</label>
            <input type="text" class="form-control @error('price') is-invalid @enderror" id="price" name="price" value="{{$product->price}}">
            @error('price')
            <p class="text-danger">{{ $message }}</p>
            @enderror
        </div>

        <div class="form-group">
            <label for="quantity">Количество</label>
            <input type="text" class="form-control @error('quantity') is-invalid @enderror" id="quantity" name="quantity" value="{{$product->quantity}}">
            @error('quantity')
            <p class="text-danger">{{ $message }}</p>
            @enderror
        </div>

        <div class="form-group">
            <label for="body">Описание</label>
            <textarea class="form-control @error('body') is-invalid @enderror" id="body" name="body" rows="3">{{$product->body}}</textarea>
            @error('body')
            <p class="text-danger">{{ $message }}</p>
            @enderror
        </div>

        <button type="submit" class="btn btn-success">Редактировать</button>

    </form>

    <div class="mt-3 mb-3">
        <a href="{{route('index')}}">Назад</a>
    </div>

@endsection

resources/views/products/show.blade.php
@extends('layouts.app')

@section('content')

    <div class="card" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">{{$product->name}}</h5>
            <h6 class="card-subtitle mb-2 text-muted">{{$product->category_of_products->name}}</h6>
            <h6 class="card-subtitle mb-2 text-muted">Цена: {{$product->price}}</h6>
            <h6 class="card-subtitle mb-2 text-muted">Количество: {{$product->quantity}}</h6>
            <p class="card-text">{{$product->body}}</p>
            @can('viewAny', Auth::User())
            <a href="{{route('products.edit', ['product' => $product])}}" class="card-link">Редактировать</a>

            <form class="card-link" method="post" action="{{route('products.destroy', ['product' => $product])}}">
                @method('delete')
                @csrf
                <button type="submit" class="btn btn-outline-danger card-link">Удалить</button>
            </form>
            @endcan
        </div>
    </div>

    <div class="mt-3 mb-3">
        <a href="{{route('index')}}">Назад</a>
    </div>

@endsection